#!/bin/bash

usage() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE

Usage: ${0##*/} [OPTION]
options:
  -help

* If single file is large ~TB, use this script

* just followed by the folder name


USAGE
    exit 1
}

# report usage
[ "$1" = "-h" -o "$1" = "-help" ] && usage


lfs setstripe -c -1 $1.tar.gz; 
tar cf - $1 | pigz -9 -p 24 > $1.tar.gz;
echo "Tar return = ${PIPESTATUS[0]}"

## if "Tar return = 0" is not output, you know the tar command failed.
